name: Build, Test, and Deploy 👩‍💻

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fschossler/basic-flask-app:${{ github.sha }} .

      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

      - name: Push Docker image to Docker Hub
        run: docker push fschossler/basic-flask-app:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v3'
  
      - name: Authenticate in GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          service_account: 'basic-flask-app@training-gcp-cloud.iam.gserviceaccount.com'
  
      - name: Deploy to Cloud Run
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'basic-flask-app'
          image: 'fschossler/basic-flask-app:${{ github.sha }}'
  
      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}/hello"'